# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DCXmeters.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MeterDialog(object):
    def setupUi(self, MeterDialog):
        MeterDialog.setObjectName("MeterDialog")
        MeterDialog.resize(249, 146)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MeterDialog.sizePolicy().hasHeightForWidth())
        MeterDialog.setSizePolicy(sizePolicy)
        self.meters_horizontalLayout = QtWidgets.QHBoxLayout(MeterDialog)
        self.meters_horizontalLayout.setContentsMargins(0, 8, 0, 2)
        self.meters_horizontalLayout.setSpacing(0)
        self.meters_horizontalLayout.setObjectName("meters_horizontalLayout")
        self.frame = QtWidgets.QFrame(MeterDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(20, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Clip = QtWidgets.QProgressBar(self.frame)
        self.Clip.setMaximumSize(QtCore.QSize(16, 20))
        self.Clip.setMaximum(1)
        self.Clip.setProperty("value", 0)
        self.Clip.setTextVisible(False)
        self.Clip.setOrientation(QtCore.Qt.Vertical)
        self.Clip.setObjectName("Clip")
        self.verticalLayout.addWidget(self.Clip)
        self.Limit = QtWidgets.QProgressBar(self.frame)
        self.Limit.setMaximumSize(QtCore.QSize(16, 20))
        self.Limit.setMaximum(1)
        self.Limit.setProperty("value", 0)
        self.Limit.setTextVisible(False)
        self.Limit.setOrientation(QtCore.Qt.Vertical)
        self.Limit.setObjectName("Limit")
        self.verticalLayout.addWidget(self.Limit)
        self.Meter_4 = QtWidgets.QProgressBar(self.frame)
        self.Meter_4.setMaximumSize(QtCore.QSize(16, 20))
        self.Meter_4.setMaximum(1)
        self.Meter_4.setProperty("value", 0)
        self.Meter_4.setTextVisible(False)
        self.Meter_4.setOrientation(QtCore.Qt.Vertical)
        self.Meter_4.setObjectName("Meter_4")
        self.verticalLayout.addWidget(self.Meter_4)
        self.Meter_3 = QtWidgets.QProgressBar(self.frame)
        self.Meter_3.setMaximumSize(QtCore.QSize(16, 20))
        self.Meter_3.setMaximum(1)
        self.Meter_3.setProperty("value", 0)
        self.Meter_3.setTextVisible(False)
        self.Meter_3.setOrientation(QtCore.Qt.Vertical)
        self.Meter_3.setObjectName("Meter_3")
        self.verticalLayout.addWidget(self.Meter_3)
        self.Meter_2 = QtWidgets.QProgressBar(self.frame)
        self.Meter_2.setMaximumSize(QtCore.QSize(16, 20))
        self.Meter_2.setMaximum(1)
        self.Meter_2.setProperty("value", 0)
        self.Meter_2.setTextVisible(False)
        self.Meter_2.setOrientation(QtCore.Qt.Vertical)
        self.Meter_2.setObjectName("Meter_2")
        self.verticalLayout.addWidget(self.Meter_2)
        self.Meter_1 = QtWidgets.QProgressBar(self.frame)
        self.Meter_1.setMaximumSize(QtCore.QSize(16, 20))
        self.Meter_1.setMaximum(1)
        self.Meter_1.setProperty("value", 0)
        self.Meter_1.setTextVisible(False)
        self.Meter_1.setOrientation(QtCore.Qt.Vertical)
        self.Meter_1.setObjectName("Meter_1")
        self.verticalLayout.addWidget(self.Meter_1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.meters_horizontalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(MeterDialog)
        QtCore.QMetaObject.connectSlotsByName(MeterDialog)

    def retranslateUi(self, MeterDialog):
        _translate = QtCore.QCoreApplication.translate
        MeterDialog.setWindowTitle(_translate("MeterDialog", "Levels"))
        self.label.setText(_translate("MeterDialog", "A"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MeterDialog = QtWidgets.QDialog()
    ui = Ui_MeterDialog()
    ui.setupUi(MeterDialog)
    MeterDialog.show()
    sys.exit(app.exec_())
