# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DCXlevelsUnit.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
from PyQt5.Qwt import *


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LevelsFrame(object):
    def setupUi(self, LevelsFrame):
        LevelsFrame.setObjectName("LevelsFrame")
        LevelsFrame.resize(181, 430)
        LevelsFrame.setToolTipDuration(-1)
        self.verticalLayoutDEBUG = QtWidgets.QVBoxLayout(LevelsFrame)
        self.verticalLayoutDEBUG.setObjectName("verticalLayoutDEBUG")
        self.frame_level_main_ch = QtWidgets.QFrame(LevelsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_level_main_ch.sizePolicy().hasHeightForWidth())
        self.frame_level_main_ch.setSizePolicy(sizePolicy)
        self.frame_level_main_ch.setMinimumSize(QtCore.QSize(156, 0))
        self.frame_level_main_ch.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.frame_level_main_ch.setFont(font)
        self.frame_level_main_ch.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_level_main_ch.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_level_main_ch.setObjectName("frame_level_main_ch")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_level_main_ch)
        self.verticalLayout_3.setContentsMargins(6, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter_levels_ch = QtWidgets.QSplitter(self.frame_level_main_ch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_levels_ch.sizePolicy().hasHeightForWidth())
        self.splitter_levels_ch.setSizePolicy(sizePolicy)
        self.splitter_levels_ch.setOrientation(QtCore.Qt.Vertical)
        self.splitter_levels_ch.setChildrenCollapsible(True)
        self.splitter_levels_ch.setObjectName("splitter_levels_ch")
        self.frame_levels_ch = QtWidgets.QFrame(self.splitter_levels_ch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_levels_ch.sizePolicy().hasHeightForWidth())
        self.frame_levels_ch.setSizePolicy(sizePolicy)
        self.frame_levels_ch.setMaximumSize(QtCore.QSize(300, 200))
        self.frame_levels_ch.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_levels_ch.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_levels_ch.setObjectName("frame_levels_ch")
        self.gridLayout_gains_chA = QtWidgets.QGridLayout(self.frame_levels_ch)
        self.gridLayout_gains_chA.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_gains_chA.setObjectName("gridLayout_gains_chA")
        self.widget_gains = QtWidgets.QWidget(self.frame_levels_ch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_gains.sizePolicy().hasHeightForWidth())
        self.widget_gains.setSizePolicy(sizePolicy)
        self.widget_gains.setObjectName("widget_gains")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_gains)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Hi_gain_remote = QwtKnob(self.widget_gains)
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Hi_gain_remote.setFont(font)
        self.Hi_gain_remote.setLowerBound(-15.0)
        self.Hi_gain_remote.setUpperBound(15.0)
        self.Hi_gain_remote.setScaleMaxMajor(6)
        self.Hi_gain_remote.setScaleMaxMinor(1)
        self.Hi_gain_remote.setTotalSteps(300)
        self.Hi_gain_remote.setKnobStyle(QwtKnob.Styled)
        self.Hi_gain_remote.setKnobWidth(40)
        self.Hi_gain_remote.setTotalAngle(270.0)
        self.Hi_gain_remote.setMarkerStyle(QwtKnob.Tick)
        self.Hi_gain_remote.setMarkerSize(12)
        self.Hi_gain_remote.setBorderWidth(2)
        self.Hi_gain_remote.setObjectName("Hi_gain_remote")
        self.gridLayout_4.addWidget(self.Hi_gain_remote, 0, 0, 1, 1)
        self.label_Gain_ch3 = QtWidgets.QLabel(self.widget_gains)
        self.label_Gain_ch3.setObjectName("label_Gain_ch3")
        self.gridLayout_4.addWidget(self.label_Gain_ch3, 1, 2, 1, 1)
        self.label_Gain_ch5 = QtWidgets.QLabel(self.widget_gains)
        self.label_Gain_ch5.setObjectName("label_Gain_ch5")
        self.gridLayout_4.addWidget(self.label_Gain_ch5, 0, 2, 1, 1)
        self.Mid_gain_remote = QwtKnob(self.widget_gains)
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Mid_gain_remote.setFont(font)
        self.Mid_gain_remote.setLowerBound(-15.0)
        self.Mid_gain_remote.setUpperBound(15.0)
        self.Mid_gain_remote.setScaleMaxMajor(6)
        self.Mid_gain_remote.setScaleMaxMinor(1)
        self.Mid_gain_remote.setTotalSteps(300)
        self.Mid_gain_remote.setKnobStyle(QwtKnob.Styled)
        self.Mid_gain_remote.setKnobWidth(40)
        self.Mid_gain_remote.setMarkerStyle(QwtKnob.Tick)
        self.Mid_gain_remote.setMarkerSize(12)
        self.Mid_gain_remote.setBorderWidth(2)
        self.Mid_gain_remote.setObjectName("Mid_gain_remote")
        self.gridLayout_4.addWidget(self.Mid_gain_remote, 1, 0, 1, 1)
        self.gridLayout_gains_chA.addWidget(self.widget_gains, 0, 0, 1, 1)
        self.frame_level_ch = QtWidgets.QFrame(self.splitter_levels_ch)
        self.frame_level_ch.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_level_ch.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_level_ch.setObjectName("frame_level_ch")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_level_ch)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setSpacing(0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_Gain_ch = QtWidgets.QLabel(self.frame_level_ch)
        self.label_Gain_ch.setObjectName("label_Gain_ch")
        self.gridLayout_15.addWidget(self.label_Gain_ch, 4, 1, 1, 1)
        self.Gain_ch = QwtKnob(self.frame_level_ch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gain_ch.sizePolicy().hasHeightForWidth())
        self.Gain_ch.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Gain_ch.setFont(font)
        self.Gain_ch.setStyleSheet("")
        self.Gain_ch.setLowerBound(-15.0)
        self.Gain_ch.setUpperBound(15.0)
        self.Gain_ch.setScaleMaxMajor(6)
        self.Gain_ch.setScaleMaxMinor(5)
        self.Gain_ch.setScaleStepSize(0.0)
        self.Gain_ch.setTotalSteps(300)
        self.Gain_ch.setPageSteps(1)
        self.Gain_ch.setKnobStyle(QwtKnob.Styled)
        self.Gain_ch.setKnobWidth(92)
        self.Gain_ch.setTotalAngle(270.0)
        self.Gain_ch.setNumTurns(1)
        self.Gain_ch.setMarkerStyle(QwtKnob.Tick)
        self.Gain_ch.setMarkerSize(12)
        self.Gain_ch.setBorderWidth(3)
        self.Gain_ch.setObjectName("Gain_ch")
        self.gridLayout_15.addWidget(self.Gain_ch, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.splitter_levels_ch)
        self.EqNumber_ch = QtWidgets.QSpinBox(self.frame_level_main_ch)
        self.EqNumber_ch.setMaximumSize(QtCore.QSize(600, 16777215))
        self.EqNumber_ch.setFrame(True)
        self.EqNumber_ch.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.EqNumber_ch.setSuffix("")
        self.EqNumber_ch.setMinimum(0)
        self.EqNumber_ch.setMaximum(9)
        self.EqNumber_ch.setProperty("value", 4)
        self.EqNumber_ch.setObjectName("EqNumber_ch")
        self.verticalLayout_3.addWidget(self.EqNumber_ch)
        self.verticalLayoutDEBUG.addWidget(self.frame_level_main_ch)

        self.retranslateUi(LevelsFrame)
        QtCore.QMetaObject.connectSlotsByName(LevelsFrame)

    def retranslateUi(self, LevelsFrame):
        _translate = QtCore.QCoreApplication.translate
        LevelsFrame.setWindowTitle(_translate("LevelsFrame", "Frame"))
        self.label_Gain_ch3.setText(_translate("LevelsFrame", "Mids"))
        self.label_Gain_ch5.setText(_translate("LevelsFrame", "Highs"))
        self.label_Gain_ch.setText(_translate("LevelsFrame", "In vol A"))
        self.EqNumber_ch.setPrefix(_translate("LevelsFrame", "Eq\'s: "))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LevelsFrame = QtWidgets.QFrame()
    ui = Ui_LevelsFrame()
    ui.setupUi(LevelsFrame)
    LevelsFrame.show()
    sys.exit(app.exec_())
