#!/usr/bin/bash
    ## generate python-ui file from yaml-ui file:
# exec python3 -m PyQt5.uic.pyuic DCX.ui -o gui_dcx.py -x & exec python3 -m PyQt5.uic.pyuic DCXeqUnit.ui -o gui_eqUnit.py -x & exec python3 -m PyQt5.uic.pyuic DCXmeters.ui -o gui_meters.py -x


python3 -m PyQt5.uic.pyuic DCX.ui -o gui_dcx.py -x 
python3 -m PyQt5.uic.pyuic DCXeqUnit.ui -o gui_eqUnit.py -x 
python3 -m PyQt5.uic.pyuic DCXmeters.ui -o gui_meters.py -x
# python3 -m PyQt5.uic.pyuic DCXlevelsUnit.ui -o gui_levelsUnit.py -x

#### Qwt Fixes ####
sed -i 's/from qwt_knob import QwtKnob//g' gui_dcx.py
sed -i 's/from qwt_dial import QwtDial//g' gui_dcx.py
sed -i 's/from qwt_wheel import QwtWheel//g' gui_dcx.py
sed -i 's/from qwt_slider import QwtSlider//g' gui_dcx.py
sed -i 's/# run again.  Do not edit this file unless you know what you are doing./from PyQt5.Qwt import */g' gui_dcx.py

sed -i 's/from qwt_knob import QwtKnob//g' gui_eqUnit.py
sed -i 's/from qwt_dial import QwtDial//g' gui_eqUnit.py
sed -i 's/from qwt_wheel import QwtWheel//g' gui_eqUnit.py
sed -i 's/from qwt_slider import QwtSlider//g' gui_eqUnit.py
sed -i 's/# run again.  Do not edit this file unless you know what you are doing./from PyQt5.Qwt import */g' gui_eqUnit.py

# sed -i 's/from qwt_knob import QwtKnob//g' gui_levelsUnit.py
# sed -i 's/from qwt_dial import QwtDial//g' gui_levelsUnit.py
# sed -i 's/from qwt_wheel import QwtWheel//g' gui_levelsUnit.py
# sed -i 's/from qwt_slider import QwtSlider//g' gui_levelsUnit.py
# sed -i 's/# run again.  Do not edit this file unless you know what you are doing./from PyQt5.Qwt import */g' gui_levelsUnit.py

sed -i 's/from qwt_thermo import QwtThermo//g' gui_meters.py
sed -i 's/# run again.  Do not edit this file unless you know what you are doing./from PyQt5.Qwt import */g' gui_meters.py


Date=`date "+ %T"`
echo -e "\n Gui .py Files Updated at: " 
echo $Date
echo -e "\n"

  ## Create package:
# pyinstaller --onefile --paths=D:/lib/python3/dist-packages  ./mainDCX.py




# Dial needle missing, This Needs adding somewhere...
# self.needle = QwtDialSimpleNeedle(
# 	QwtDialSimpleNeedle.Arrow, True, QtCore.Qt.gray,
# 	QtCore.Qt.gray )#.light( 130 ) )
# self.Gain_chA_3.setNeedle( self.needle )



# sed -i 's/QwtKnob(self/Qwt.QwtKnob(self/g' gui_dcx.py
# sed -i 's/QwtDial(self./Qwt.QwtDial(self./g' gui_dcx.py
# 
# sed -i 's/(QwtKnob.Styled)/(Qwt.QwtKnob.Styled)/g' gui_dcx.py
# sed -i 's/(QwtKnob.Tick)/(Qwt.QwtKnob.Tick)/g' gui_dcx.py
# sed -i 's/(QwtDial.RotateScale)/(Qwt.QwtDial.RotateScale)/g' gui_dcx.py






# sleep 1 
    ## Bash script to Automate this:
# watch -n2 "watch -d -t -g ls -lR ./DCX.ui && ./GuiPyGen.sh"




    ## some reminders of some things
#         self.setWindowFlag(QtCore.Qt.FramelessWindowHint)
#         self.setWindowFlag(QtCore.Qt.WindowCloseButtonHint, False)

# watch -d od -A x -t x1z -v /dev/ttyUSB0
# watch -d od -A x -t x1z -v ./dumpwatch0

# Find/Replace...
# sed -i 's/<search regex>/<replacement>/g' <input file>
